// Generated by CoffeeScript 1.7.1
var app, express, io, port;

express = require('express');

app = express();

port = 4839;

app.set('views', "" + __dirname + "/tpl");

app.set('view engine', 'html');

app.engine('html', require('ejs').__express);

app.get('/', function(request, respond) {
  return respond.render('page');
});

app.use(express["static"]("" + __dirname + "/public"));

io = require('socket.io').listen(app.listen(port));

io.sockets.on('connection', function(socket) {
  socket.emit('message', {
    message: 'welcome to the chat'
  });
  return socket.on('send', function(data) {
    return io.sockets.emit('message', data);
  });
});

console.log("Listening on port " + port);
